In [1]:
from sklearn.linear_model import SGDRegressor
from sklearn.datasets import make_regression
X,y,coef=make_regression(n_samples=1000,n_features=5,noise=2,bias=0,random_state=2323,coef=True)
print('real coef',coef)
#eta0:初始学习率
sgd=SGDRegressor(eta0=0.2)
sgd.fit(X,y)
print('拟合coef',sgd.coef_)
print('拟合bias',sgd.intercept_)

real coef [44.23303928 32.21564911  3.64297323 53.78792964 56.44109417]
拟合coef [43.74461642 32.04357952  3.8051838  53.80051612 56.89398898]
拟合bias [0.19933532]

In [20]:
import pandas as pd
from sklearn.linear_model import LinearRegression
data=pd.read_csv('../data/house.csv')
display(data.head())
X,y=data.iloc[:,:-1],data['MEDV']
lr=LinearRegression()
lr.fit(X,y)
print(lr.coef_)
print(lr.intercept_)
print(lr.score(X,y))

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

[-1.08011358e-01  4.64204584e-02  2.05586264e-02  2.68673382e+00
 -1.77666112e+01  3.80986521e+00  6.92224640e-04 -1.47556685e+00
  3.06049479e-01 -1.23345939e-02 -9.52747232e-01  9.31168327e-03
 -5.24758378e-01]
36.45948838508985
0.7406426641094094

In [ ]:
from sklearn.preprocessing import StandardScaler
import numpy as np
#将数据的各个特征转换成均值为0,标准差为1的形式
#内部计算:每个特征,(特征-特征均值)/特征标准差
a=np.array([5,3,8,4,6,-2])
print(a.mean())
b=a-a.mean()
print(b.mean())
#数组中每个元素乘除一个值,则该数组的标准差也会乘除该值
print(a.std())
c=a*2
print(c.std())
d=a/a.std()
print(d.std())

4.0
0.0
3.1091263510296048
6.2182527020592095
1.0

In [18]:
s = StandardScaler()
# fit学习转换规则，该规则为每个特征列的均值与标准差。
# 学习的规则通过属性来存储。
s.fit(X)
# 从训练集中学习的均值与方差。
print(s.mean_)
print(s.var_)
# 利用训练集学习到的转换规则，就可以对任意的未知数据进行转换。
X_scale = s.transform(X)
df = pd.DataFrame(X_scale, columns=X.columns)
df.head()

[3.61352356e+00 1.13636364e+01 1.11367787e+01 6.91699605e-02
 5.54695059e-01 6.28463439e+00 6.85749012e+01 3.79504269e+00
 9.54940711e+00 4.08237154e+02 1.84555336e+01 3.56674032e+02
 1.26530632e+01]
[7.38403597e+01 5.42861840e+02 4.69714297e+01 6.43854770e-02
 1.34010989e-02 4.92695216e-01 7.90792473e+02 4.42525226e+00
 7.56665313e+01 2.83486236e+04 4.67772630e+00 8.31828042e+03
 5.08939794e+01]

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,-0.419782,0.284830,-1.287909,-0.272599,-0.144217,0.413672,-0.120013,0.140214,-0.982843,-0.666608,-1.459000,0.441052,-1.075562
1,-0.417339,-0.487722,-0.593381,-0.272599,-0.740262,0.194274,0.367166,0.557160,-0.867883,-0.987329,-0.303094,0.441052,-0.492439
2,-0.417342,-0.487722,-0.593381,-0.272599,-0.740262,1.282714,-0.265812,0.557160,-0.867883,-0.987329,-0.303094,0.396427,-1.208727
3,-0.416750,-0.487722,-1.306878,-0.272599,-0.835284,1.016303,-0.809889,1.077737,-0.752922,-1.106115,0.113032,0.416163,-1.361517
4,-0.412482,-0.487722,-1.306878,-0.272599,-0.835284,1.228577,-0.511180,1.077737,-0.752922,-1.106115,0.113032,0.441052,-1.026501

In [19]:
# 是否标准化，不会影响到线性回归的拟合优度（R^2值），但是会影响线性回归拟合的参数（权重与偏置）。
lr.fit(X_scale, y)
print(lr.coef_)
print(lr.intercept_)
print(lr.score(X_scale, y))

[-0.92814606  1.08156863  0.1409      0.68173972 -2.05671827  2.67423017
  0.01946607 -3.10404426  2.66221764 -2.07678168 -2.06060666  0.84926842
 -3.74362713]
22.532806324110677
0.7406426641094094

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
lr = LinearRegression()
lr.fit(X_train, y_train)
print("线性回归拟合结果：")
print(lr.score(X_train, y_train))
print(lr.score(X_test, y_test))

sgd = SGDRegressor(eta0=0.01)
sgd.fit(X_train, y_train)
print("梯度法拟合结果：")
print(sgd.score(X_train, y_train))
print(sgd.score(X_test, y_test))

线性回归拟合结果：
0.7645451026942548
0.6733825506400158
梯度法拟合结果：
-3.7556588328502475e+25
-4.344765756594306e+25

In [23]:
from sklearn.pipeline import Pipeline
pipe = Pipeline([("scale", StandardScaler()), 
                 ("sgd", SGDRegressor(eta0=0.01))])
pipe.fit(X_train, y_train)
print(pipe.score(X_train, y_train))
print(pipe.score(X_test, y_test))

0.7633158227854362
0.668347291523758