In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
from statsmodels.stats.weightstats import ztest
from scipy.stats import chi2_contingency
df_train=pd.read_csv('../data/new_car_train.csv')
df_train

          交易ID    交易名称    汽车注册日期   车型编码  ...      v_21      v_22      v_23  价格标签
0       134890     734  20160002   13.0  ...  9.077297  0.581214  3.945923   0.0
1       306648  196973  20080307   72.0  ... -3.949621  4.593618 -1.145653   0.0
2       340675   25347  20020312   18.0  ...  2.625318 -0.851922 -1.246135   0.0
3        57332    5382  20000611   38.0  ...  3.040629 -0.801854 -1.251894   0.0
4       265235  173174  20030109   87.0  ... -3.303424 -1.998466 -1.279368   0.0
...        ...     ...       ...    ...  ...       ...       ...       ...   ...
249995   10556    9332  20170003   13.0  ...  7.883413  0.698405 -1.082013   0.0
249996  146710  102110  20030511   29.0  ... -2.532968 -0.940266 -1.106426   0.0
249997  116066   82802  20130312  124.0  ... -3.872725  2.135984  3.807554   1.0
249998   90082   65971  20121212  111.0  ... -3.104789 -3.777374  3.186218   1.0
249999   76453   56954  20051111   13.0  ... -0.980042 -0.955164 -1.169593   0.0

[250000 rows x 41 columns]

In [10]:
arr=[]
for col in df_train:
    if df_train[col].nunique()>30:
        p_value=ztest(df_train.query('价格标签==0')[col],df_train.query('价格标签==1')[col])[1]
        # p_value
        arr.append(
            pd.DataFrame({
                "维度":[col],
                '检验方法':['z检验'],
                'p值':[p_value],
                '结果':['有影响' if p_value<0.05 else '没影响']
            })
        )
    else:
        p_value=chi2_contingency(df_train.groupby([col,'价格标签']).size().unstack())[1]
        arr.append(
            pd.DataFrame({
                "维度":[col],
                '检验方法':['卡方检验'],
                'p值':[p_value],
                '结果':['有影响' if p_value<0.05 else '没影响']
            })
        )
pd.concat(arr)

           维度  检验方法             p值   结果
0        交易ID   z检验   1.254935e-01  没影响
0        交易名称   z检验   1.137038e-19  有影响
0      汽车注册日期   z检验   0.000000e+00  有影响
0        车型编码   z检验   0.000000e+00  有影响
0        汽车品牌   z检验  6.138927e-172  有影响
0        车身类型  卡方检验   0.000000e+00  有影响
0        燃油类型  卡方检验   0.000000e+00  有影响
0         变速箱  卡方检验   0.000000e+00  有影响
0       发动机功率   z检验   0.000000e+00  有影响
0     汽车已行驶公里  卡方检验   0.000000e+00  有影响
0  汽车有尚未修复的损坏  卡方检验   0.000000e+00  有影响
0        地区编码   z检验   3.369272e-15  有影响
0         销售方  卡方检验            NaN  没影响
0        报价类型  卡方检验   1.000000e+00  没影响
0      汽车上线时间   z检验   7.640553e-02  没影响
0     二手车交易价格   z检验   0.000000e+00  有影响
0         v_O   z检验   0.000000e+00  有影响
0         v_1   z检验   0.000000e+00  有影响
0        v_ 2   z检验   3.749062e-11  有影响
0         v_3   z检验   0.000000e+00  有影响
0         v_4   z检验   9.143753e-01  没影响
0         v_5   z检验   4.614733e-25  有影响
0         v_6   z检验   1.168879e-20  有影响
0         v_7   z检验   0.000000e+00  有影响
0         v_8   z检验   0.000000e+00  有影响
0         v_9   z检验   0.000000e+00  有影响
0        v_10   z检验   0.000000e+00  有影响
0        v_11   z检验   0.000000e+00  有影响
0        v_12   z检验   0.000000e+00  有影响
0        v_13   z检验   0.000000e+00  有影响
0        v_14   z检验   0.000000e+00  有影响
0        v_15   z检验   0.000000e+00  有影响
0        v_16   z检验   0.000000e+00  有影响
0        v_17   z检验   0.000000e+00  有影响
0        v_18   z检验   0.000000e+00  有影响
0        v_19   z检验   1.653764e-37  有影响
0        v_20   z检验   5.424863e-69  有影响
0        v_21   z检验   5.657446e-54  有影响
0        v_22   z检验   0.000000e+00  有影响
0        v_23   z检验   7.415416e-30  有影响
0        价格标签  卡方检验            NaN  没影响